
const data = [
  {
    id: 1,
    img: "https://m.media-amazon.com/images/I/71hLIZTbrUL._AC_SX679_.jpg",
    title: "Apple iPhone 15 Plus",
    upvotes: 0,
    downvotes: 0,
    reviews: "(12.912 reviews)",
    newPrice: "$1000",
    company: "Apple",
    ram: "6gb",
    brand: "apple",
    reviews: [],
  },
  {
    id: 2,
    img: "https://m.media-amazon.com/images/I/61VuVU94RnL._AC_SX679_.jpg",
    title: "Apple iPhone 13",
    upvotes: 0,
    downvotes: 0,
    reviews: "(20.143 reviews)",
    newPrice: "$700,00",
    company: "Apple",
    ram: "6gb",
    brand: "apple",
    reviews: [],
  },
  {
    id: 3,
    img: "https://m.media-amazon.com/images/I/71VhRDv5jXL._AC_SX679_.jpg",
    title: "Samsung Galaxy S24",
    upvotes: 0,
    downvotes: 0,
    reviews: "(7.912 reviews)",
    newPrice: "$500,00",
    company: "Samsung",
    ram: "8gb",
    brand: "samsung",
    reviews: [],
  },
  {
    id: 4,
    img: "https://m.media-amazon.com/images/I/51IynDkhy8L.__AC_SX300_SY300_QL70_ML2_.jpg",
    title: "Samsung Galaxy A24",
    upvotes: 0,
    downvotes: 0,
    reviews: "(2.225 reviews)",
    newPrice: "$99,99",
    company: "Samsung",
    ram: "6gb",
    brand: "samsung",
    reviews: [],
  },
  {
    id: 5,
    img: "https://m.media-amazon.com/images/I/51bw39q0AzL.__AC_SX300_SY300_QL70_ML2_.jpg",
    title: "Xiaomi Redmi 10",
    upvotes: 0,
    downvotes: 0,
    reviews: "(1.090 reviews)",
    newPrice: "$55,00",
    company: "Xiaomi",
    ram: "4gb",
    brand: "xiaomi",
    reviews: [],
  },
  {
    id: 6,
    img: "https://m.media-amazon.com/images/I/71r5FZWh06L._AC_SX679_.jpg",
    title: "Reeder P13 Plus",
    upvotes: 0,
    downvotes: 0,
    reviews: "(992 reviews)",
    newPrice: "$60,00",
    company: "Reeder",
    ram: "4gb",
    brand: "reeder",
    reviews: [],
  },
  
];

export default data;
